name: dateparser
description: Dart library for parsing relative date and time.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies: 
  characters: ^1.2.1
  yaml: ^3.1.1
  benchmark_harness: ^2.1.0

  dateparser_core:
    path: packages/dateparser_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

  build_runner:
  dateparser_generators:
    path: packages/dateparser_generators
