name: rechron
description: Dart library for parsing relative date and time.
version: 0.2.0
repository: https://github.com/mensch272/rechron

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  benchmark_harness: ^2.1.0
  rechron_core: ^0.2.0

dependency_overrides:
  rechron_core:
    path: ../rechron_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0

  build_runner:
  rechron_dev:
    path: ../rechron_dev
