name: dateparser_generators
description: A starting point for Dart libraries or applications.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0-165.1.beta <3.0.0'

dependencies:
  build:
  source_gen:
  glob: ^2.1.0
  code_builder: ^4.1.0
  path: ^1.8.2
  dart_style: ^2.2.3
  yaml: ^3.1.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
