name: rechron_dev
description: This library contains generators used in rechron.
version: 0.1.1-dev.1
repository: https://github.com/mensch272/rechron

publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  build:
  source_gen:
  glob: ^2.1.0
  code_builder: ^4.1.0
  path: ^1.8.2
  dart_style: ^2.2.3
  yaml: ^3.1.1
  rechron_core:
    path: ../rechron_core

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
